databases:
  - name: djangocrud
    plan: free
    databaseName: djangocrud
    user: djangocrud

services:
  - type: web
    plan: free
    name: djangocrud
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn djangocrud.asgi:application -k uvicorn.workers.UvicornWorker"    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: djangocrud
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4